In [196]:
import numpy as np

# Code for numpy

a=

In [10]:
a=np.array([1,2,3])

In [11]:
a.ndim

1

In [8]:
b=np.array(
    [
    [1,2,3],
    [4,5,6]
    ])


In [14]:
b.ndim

2

In [15]:
c=np.array(
  [ [
    [1,2,3],
    [4,5,6]
    ],
        [
    [1,2,3],
    [4,5,6]
    ]])


In [16]:
c.ndim

3

In [18]:
d=np.array(
 [ [ [
    [1,2,3],
    [4,5,6]
    ],
        [
    [1,2,3],
    [4,5,6]
    ]],
    [ [
    [1,2,3],
    [4,5,6]
    ],
        [
    [1,2,3],
    [4,5,6]
    ]]])

In [19]:
d.ndim

4

In [20]:
d

array([[[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]]])

In [22]:
a.shape,b.shape,c.shape,d.shape

((3,), (2, 3), (2, 2, 3), (2, 2, 2, 3))

In [24]:
a.dtype,b.dtype,c.dtype,d.dtype

(dtype('int32'), dtype('int32'), dtype('int32'), dtype('int32'))

In [25]:
tuple(a)

(1, 2, 3)

In [10]:
a=np.array([
    0.2,0.4,0.5
])

In [12]:
a

array([0.2, 0.4, 0.5])

In [13]:
a.dtype

dtype('float64')

In [15]:
a=np.array([1,2,3])
print(a.dtype)

int32


In [16]:
import pandas as pd

# DataFrame using Numpy array

In [17]:
df=pd.DataFrame(a)

In [18]:
df

0
0  1
1  2
2  3

In [19]:
on=np.ones((3,3))


In [20]:
on

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
print(on[0][0])

1.0


In [22]:
zeroes=np.zeros((2,3,4))

In [23]:
zeroes

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
rangearray=np.arange(0,20,2)

In [25]:
rangearray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
random=np.random.randint(0,20,size=(2,2))

In [29]:
random

array([[18, 16],
       [10, 12]])

In [30]:
random.size

4

In [31]:
random.shape

(2, 2)

In [32]:
r=np.random.random(size=(2,2))

In [33]:
r

array([[0.68847579, 0.34506022],
       [0.04401034, 0.08638392]])

In [77]:
np.random.seed(2)
random_array_2 = np.random.randint(0,200,size=(5, 3))
random_array_2

array([[168,  15,  72],
       [ 22,  43,  75],
       [104,   7, 162],
       [177,  95,  75],
       [ 47,  63,  31]])

In [79]:
np.random.seed(2)
ra=np.random.randint(0,200,size=(5, 3))
ra

array([[168,  15,  72],
       [ 22,  43,  75],
       [104,   7, 162],
       [177,  95,  75],
       [ 47,  63,  31]])

In [80]:
a=pd.DataFrame(ra)

In [81]:
a

0   1    2
0  168  15   72
1   22  43   75
2  104   7  162
3  177  95   75
4   47  63   31

In [84]:
ra[:1,:2]

array([[168,  15]])

In [85]:
rb=np.random.randint(0,200,size=(5, 3))

In [86]:
ra=ra+rb

In [87]:
ra

array([[316, 139, 188],
       [ 59, 210, 270],
       [206,  11, 332],
       [284, 146, 178],
       [ 85,  96,  89]])

In [88]:
ra

array([[316, 139, 188],
       [ 59, 210, 270],
       [206,  11, 332],
       [284, 146, 178],
       [ 85,  96,  89]])

In [89]:
ra

array([[316, 139, 188],
       [ 59, 210, 270],
       [206,  11, 332],
       [284, 146, 178],
       [ 85,  96,  89]])

In [90]:
ra

array([[316, 139, 188],
       [ 59, 210, 270],
       [206,  11, 332],
       [284, 146, 178],
       [ 85,  96,  89]])

In [91]:
ra=ra-rb

In [92]:
ra

array([[168,  15,  72],
       [ 22,  43,  75],
       [104,   7, 162],
       [177,  95,  75],
       [ 47,  63,  31]])

In [93]:
ra=ra-rb
ra

array([[  20, -109,  -44],
       [ -15, -124, -120],
       [   2,    3,   -8],
       [  70,   44,  -28],
       [   9,   30,  -27]])

In [94]:
ra=ra*8

In [95]:
ra

array([[ 160, -872, -352],
       [-120, -992, -960],
       [  16,   24,  -64],
       [ 560,  352, -224],
       [  72,  240, -216]])

In [107]:
ra=rb.copy()
ra,rb

(array([[148, 124, 116],
        [ 37, 167, 195],
        [102,   4, 170],
        [107,  51, 103],
        [ 38,  33,  58]]),
 array([[148, 124, 116],
        [ 37, 167, 195],
        [102,   4, 170],
        [107,  51, 103],
        [ 38,  33,  58]]))

In [108]:
ra=ra*rb

In [109]:
ra

array([[21904, 15376, 13456],
       [ 1369, 27889, 38025],
       [10404,    16, 28900],
       [11449,  2601, 10609],
       [ 1444,  1089,  3364]])

In [129]:
a=np.random.randint(0,200,size=(5, 4,5))
b=np.random.randint(0,200,size=( 4,5))
a,b

(array([[[192, 102, 154,  78, 113],
         [127, 104,  14,  69, 113],
         [144,   5,   8, 114,  14],
         [118,  91, 169,  93,  47]],
 
        [[ 73, 168,  76,  97,  81],
         [194,  98, 188, 139,  15],
         [ 83,  91,  25, 100, 173],
         [ 36, 160,  96, 132,  12]],
 
        [[ 23, 125, 133,  94,  90],
         [ 41, 150, 187,  27,  38],
         [ 24,  50, 154,  92, 159],
         [167,  43, 173, 125, 133]],
 
        [[  7,   6,  73,  83, 144],
         [148, 112, 155, 159,  76],
         [110, 137,  20, 103, 150],
         [133,   9,  21,  28, 117]],
 
        [[169, 178,  46, 121,  52],
         [104,  66, 193, 122, 102],
         [145,  25,  35,  25,  98],
         [194, 136, 194,  53, 146]]]),
 array([[122,  38,   5, 160,  85],
        [ 79, 138,  58, 131, 138],
        [ 41, 112, 151,  44, 159],
        [106, 165, 135,  96,  60]]))

In [130]:
a+b

array([[[314, 140, 159, 238, 198],
        [206, 242,  72, 200, 251],
        [185, 117, 159, 158, 173],
        [224, 256, 304, 189, 107]],

       [[195, 206,  81, 257, 166],
        [273, 236, 246, 270, 153],
        [124, 203, 176, 144, 332],
        [142, 325, 231, 228,  72]],

       [[145, 163, 138, 254, 175],
        [120, 288, 245, 158, 176],
        [ 65, 162, 305, 136, 318],
        [273, 208, 308, 221, 193]],

       [[129,  44,  78, 243, 229],
        [227, 250, 213, 290, 214],
        [151, 249, 171, 147, 309],
        [239, 174, 156, 124, 177]],

       [[291, 216,  51, 281, 137],
        [183, 204, 251, 253, 240],
        [186, 137, 186,  69, 257],
        [300, 301, 329, 149, 206]]])

In [131]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [132]:
%timeit sum(massive_array) # Python sum()
%timeit np.sum(massive_array) # NumPy np.sum()

17.3 ms ± 884 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
89.2 µs ± 9.36 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [133]:
import random 
massive_list = [random.randint(0, 10) for i in range(100000)]
len(massive_list)

100000

In [134]:
%timeit sum(massive_list)
%timeit np.sum(massive_list)

1.51 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
15.6 ms ± 580 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [139]:
zeroes=np.random.randint(0,20,size=(2,3))


In [145]:
np.std(zeroes),np.var(zeroes),np.sqrt(np.var(zeroes))

(6.1553951042064625, 37.888888888888886, 6.1553951042064625)

In [146]:
a

array([[[192, 102, 154,  78, 113],
        [127, 104,  14,  69, 113],
        [144,   5,   8, 114,  14],
        [118,  91, 169,  93,  47]],

       [[ 73, 168,  76,  97,  81],
        [194,  98, 188, 139,  15],
        [ 83,  91,  25, 100, 173],
        [ 36, 160,  96, 132,  12]],

       [[ 23, 125, 133,  94,  90],
        [ 41, 150, 187,  27,  38],
        [ 24,  50, 154,  92, 159],
        [167,  43, 173, 125, 133]],

       [[  7,   6,  73,  83, 144],
        [148, 112, 155, 159,  76],
        [110, 137,  20, 103, 150],
        [133,   9,  21,  28, 117]],

       [[169, 178,  46, 121,  52],
        [104,  66, 193, 122, 102],
        [145,  25,  35,  25,  98],
        [194, 136, 194,  53, 146]]])

In [161]:
a=np.random.random(size=(2,3))
a


array([[0.01537059, 0.9658942 , 0.59298531],
       [0.63127459, 0.7426931 , 0.96285351]])

In [167]:
np.reshape(a,(3,2))

array([[0.01537059, 0.9658942 ],
       [0.59298531, 0.63127459],
       [0.7426931 , 0.96285351]])

In [174]:
a.T

array([[0.01537059, 0.63127459],
       [0.9658942 , 0.7426931 ],
       [0.59298531, 0.96285351]])

In [175]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [238]:
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [225]:
prices = np.array([10, 8, 12])
prices=pd.DataFrame("prices":prices)

SyntaxError: invalid syntax (733546315.py, line 2)

In [178]:
# Find the total amount of sales for a whole day
total_sales = prices.dot(sales_amounts)
total_sales


ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [179]:
sales_amounts.T.shape

(3, 5)

In [180]:
# To make the middle numbers the same, we can transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [183]:
from matplotlib.image import imread
a=imread("step-ml-framework.png")

In [184]:
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0.

In [188]:
c=a.argmin()
c

0

In [198]:
np=4

In [197]:
a=np.random.random(size=(2,3))

In [202]:
print(a.T)

[[0.52889492 0.07103606]
 [0.56804456 0.0871293 ]
 [0.92559664 0.0202184 ]]


In [207]:
a=np.random.randint(0,10,size=(2,3))

In [213]:
b=np.random.randint(0,10,size=(3,3))
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [215]:
a=np.random.randint(0,10,size=(2,3))
b=np.random.randint(0,10,size=(3))
a>5

array([[False,  True, False],
       [False,  True, False]])

In [216]:

a,b

(array([[4, 8, 4],
        [3, 7, 5]]),
 array([5, 0, 1]))

In [217]:
np.sort(a)

array([[4, 4, 8],
       [3, 5, 7]])

In [218]:
np.argsort(a)

array([[0, 2, 1],
       [0, 2, 1]], dtype=int64)

In [219]:
a

array([[4, 8, 4],
       [3, 7, 5]])

In [237]:
weekly_sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [239]:
prices=pd.Series(prices)

ValueError: Data must be 1-dimensional

In [229]:
prices=pd.DataFrame({"prices":prices})

In [230]:
prices

prices
0      10
1       8
2      12

In [231]:
weekly_sales=np.array(weekly_sales)

In [233]:
prices=np.array(prices)

In [236]:
results=np.dot(weekly_sales,prices)

In [240]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [241]:
weekly_sales["results"]=results

In [242]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  results
Mon               12             15              0      240
Tues               3              3              7      138
Wed                9             19             18      458
Thurs              4              6             12      232
Fri                1              6              7      142

In [243]:
arr=np.array([1,2,3])

In [245]:
arr.shape,arr.size,arr.ndim,arr.dtype

((3,), 3, 1, dtype('int32'))

In [246]:
df=pd.DataFrame([1,2,3,4])
df

0
0  1
1  2
2  3
3  4

In [247]:
df=np.array(df)

In [248]:
df

array([[1],
       [2],
       [3],
       [4]], dtype=int64)

In [249]:
zero=np.zeros((10,2))

In [250]:
zero

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [252]:
a=np.arange(0,10,1)

In [253]:
a=np.random.randint(0,10,size=(7,2))

In [254]:
a

array([[5, 9],
       [3, 0],
       [5, 0],
       [1, 2],
       [4, 2],
       [0, 3],
       [2, 0]])

In [260]:
np.random.seed(0)
a=np.random.random((7,2))
a

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.96366276, 0.38344152],
       [0.79172504, 0.52889492],
       [0.56804456, 0.92559664]])

In [261]:
np.unique(a)

array([0.38344152, 0.4236548 , 0.43758721, 0.52889492, 0.54488318,
       0.5488135 , 0.56804456, 0.60276338, 0.64589411, 0.71518937,
       0.79172504, 0.891773  , 0.92559664, 0.96366276])

In [262]:
a[0][0]

0.5488135039273248

In [264]:
a[:2,:2]

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [265]:
a=np.random.randint(0,10,size=(3,5))

In [266]:
b=np.ones((3,5))

In [267]:
a+b

array([[ 9., 10.,  5.,  4.,  1.],
       [ 4.,  6.,  1.,  3.,  4.],
       [ 9.,  2.,  4.,  4.,  4.]])

In [268]:
c=np.random.randint(0,10,size=(5,3))

In [269]:
b+c

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [270]:
c.reshape((3,5))

array([[7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2],
       [7, 2, 0, 0, 4]])

In [289]:
b.shape,c.shape

((3, 5), (5, 3))

In [286]:
c.reshape((3,5,1))

array([[[7],
        [0],
        [1],
        [9],
        [9]],

       [[0],
        [4],
        [7],
        [3],
        [2]],

       [[7],
        [2],
        [0],
        [0],
        [4]]])

In [292]:
c=c.reshape(3,5)

In [293]:
c

array([[7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2],
       [7, 2, 0, 0, 4]])

In [296]:
x=b+c

In [295]:
q=np.random.randint(0,19,size=(3,5))

In [297]:
x=q-x

In [298]:
x*q

array([[-15.,  30.,  48., 119.,  75.],
       [ 12.,  36.,  20.,  -3.,  -2.],
       [ -7.,  54.,   6.,  30.,  66.]])

In [299]:
np.square(x)

array([[ 9., 25., 36., 49., 25.],
       [ 9., 16.,  4.,  9.,  4.],
       [ 1., 36.,  4., 25., 36.]])

In [300]:
np.mean(x)

2.8

In [301]:
np.var(x)

11.360000000000003

In [302]:
x

array([[-3.,  5.,  6.,  7.,  5.],
       [ 3.,  4.,  2., -3., -2.],
       [-1.,  6.,  2.,  5.,  6.]])

In [304]:
x.reshape(3,5,1)

array([[[-3.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 5.]],

       [[ 3.],
        [ 4.],
        [ 2.],
        [-3.],
        [-2.]],

       [[-1.],
        [ 6.],
        [ 2.],
        [ 5.],
        [ 6.]]])